import { BaseAdapter, PriceQuery, FetchedProduct } from "./base";

const MOCK_ACTIVITIES: Record<string, FetchedProduct[]> = {
  "Santorini, Greece": [
    {
      externalId: "act-sant-001",
      name: "Private Sunset Catamaran Cruise with BBQ",
      description: "Sail the caldera on a luxury catamaran. Swim in hot springs, snorkel, and dine as the sun sets.",
      destination: "Santorini, Greece",
      country: "Greece",
      imageUrl: "https://images.unsplash.com/photo-1534445867742-43195f401b6c?w=800&h=600&fit=crop",
      reviewScore: 4.9,
      reviewCount: 1240,
      amenities: ["Open Bar", "Gourmet BBQ", "Snorkeling Gear", "Hotel Transfer", "Small Group"],
      price: 28000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-sant-002",
      name: "Volcanic Wine Tasting Tour",
      description: "Visit three family-owned vineyards. Taste Assyrtiko and Vinsanto where they're grown.",
      destination: "Santorini, Greece",
      country: "Greece",
      reviewScore: 4.8,
      reviewCount: 890,
      amenities: ["Private Driver", "5 Wines", "Local Cheese Pairing", "Cellar Tour"],
      price: 18500,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Maldives": [
    {
      externalId: "act-mal-001",
      name: "Private Sandbank Dinner Under the Stars",
      description: "Your own island. Your own chef. Candlelit dinner with nothing but bioluminescent waves.",
      destination: "Maldives",
      country: "Maldives",
      reviewScore: 5.0,
      reviewCount: 234,
      amenities: ["Private Island", "Personal Chef", "Champagne", "Stargazing Setup", "Return Boat"],
      price: 65000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-mal-002",
      name: "Manta Ray Night Snorkel",
      description: "Swim alongside gentle giants under the moonlight.",
      destination: "Maldives",
      country: "Maldives",
      reviewScore: 4.9,
      reviewCount: 567,
      amenities: ["Expert Guide", "Underwater Torch", "Wetsuit", "Hot Chocolate After"],
      price: 22000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Bali, Indonesia": [
    {
      externalId: "act-bali-001",
      name: "Private Ubud Rice Terrace Walk & Blessing",
      description: "Walk the Tegallalang terraces with a local guide, then receive a traditional Balinese blessing.",
      destination: "Bali, Indonesia",
      country: "Indonesia",
      reviewScore: 4.9,
      reviewCount: 780,
      amenities: ["Local Guide", "Blessing Ceremony", "Lunch", "Transport"],
      price: 12000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-bali-002",
      name: "Sunset Mount Batur Trek",
      description: "Hike an active volcano in darkness. Watch sunrise from the summit with a volcanic steam breakfast.",
      destination: "Bali, Indonesia",
      country: "Indonesia",
      reviewScore: 4.8,
      reviewCount: 1200,
      amenities: ["Guide", "Breakfast", "Flashlight", "Transport", "Hot Springs"],
      price: 8500,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Tulum, Mexico": [
    {
      externalId: "act-tulum-001",
      name: "Cenote Diving Experience",
      description: "Dive into crystal-clear freshwater caves. Professional guide, all gear included.",
      destination: "Tulum, Mexico",
      country: "Mexico",
      reviewScore: 4.9,
      reviewCount: 650,
      amenities: ["Professional Guide", "All Gear", "Underwater Photos", "Lunch"],
      price: 15000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-tulum-002",
      name: "Private Sian Ka'an Lagoon Tour",
      description: "Float down ancient Mayan canals through mangrove forests. Spot manatees and sea turtles.",
      destination: "Tulum, Mexico",
      country: "Mexico",
      reviewScore: 4.8,
      reviewCount: 420,
      amenities: ["Boat Tour", "Naturalist Guide", "Lunch", "Snorkeling"],
      price: 18000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Bora Bora": [
    {
      externalId: "act-bora-001",
      name: "Shark & Ray Snorkel Safari",
      description: "Feed stingrays and swim with reef sharks in the lagoon. Safe, thrilling, unforgettable.",
      destination: "Bora Bora",
      country: "French Polynesia",
      reviewScore: 4.9,
      reviewCount: 890,
      amenities: ["Marine Biologist Guide", "Snorkel Gear", "Fruit Platter", "Boat Transfer"],
      price: 28000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-bora-002",
      name: "Mount Otemanu Helicopter Tour",
      description: "Circle the island's sacred peak. See the heart-shaped atoll from above.",
      destination: "Bora Bora",
      country: "French Polynesia",
      reviewScore: 4.9,
      reviewCount: 345,
      amenities: ["Private Helicopter", "Pilot Commentary", "Champagne", "Photos"],
      price: 45000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Paris, France": [
    {
      externalId: "act-par-001",
      name: "Private Seine River Cruise with Dinner",
      description: "Your own boat. A private chef. Float past the Eiffel Tower as it sparkles.",
      destination: "Paris, France",
      country: "France",
      reviewScore: 4.9,
      reviewCount: 560,
      amenities: ["Private Boat", "Private Chef", "Champagne", "Live Music Option"],
      price: 35000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-par-002",
      name: "Couples Cooking Class at Le Cordon Bleu",
      description: "Learn to make macarons and coq au vin from a master chef.",
      destination: "Paris, France",
      country: "France",
      reviewScore: 4.8,
      reviewCount: 420,
      amenities: ["Master Chef", "Wine Pairing", "Recipe Book", "Aprons"],
      price: 22000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Dubai, UAE": [
    {
      externalId: "act-dub-001",
      name: "Desert Safari with Private Camp",
      description: "Dune bashing, falconry, and a private Bedouin-style dinner under the stars.",
      destination: "Dubai, UAE",
      country: "UAE",
      reviewScore: 4.8,
      reviewCount: 1500,
      amenities: ["Private Camp", "Falcon Show", "Camel Ride", "BBQ Dinner", "Belly Dance"],
      price: 18000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-dub-002",
      name: "Private Yacht Charter on the Marina",
      description: "2-hour sunset cruise past the Burj Al Arab and Palm Jumeirah.",
      destination: "Dubai, UAE",
      country: "UAE",
      reviewScore: 4.9,
      reviewCount: 780,
      amenities: ["Captain & Crew", "Champagne", "Canapés", "Swim Stop"],
      price: 25000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Tromsø, Norway": [
    {
      externalId: "act-nor-001",
      name: "Northern Lights Chase by Snowmobile",
      description: "Ride into the wilderness, build a fire, and wait for the aurora to dance.",
      destination: "Tromsø, Norway",
      country: "Norway",
      reviewScore: 4.8,
      reviewCount: 670,
      amenities: ["Snowmobile", "Warm Suits", "Hot Drinks", "Guide", "Photos"],
      price: 22000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-nor-002",
      name: "Husky Sledding Under the Stars",
      description: "Mush your own team of huskies through silent snow forests.",
      destination: "Tromsø, Norway",
      country: "Norway",
      reviewScore: 4.9,
      reviewCount: 890,
      amenities: ["Your Own Team", "Guide", "Warm Meal After", "Photos", "Arctic Suit"],
      price: 18000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
  "Kenya": [
    {
      externalId: "act-ken-001",
      name: "Hot Air Balloon Safari at Dawn",
      description: "Float over the Mara at sunrise. See the Great Migration from above. Champagne breakfast in the bush.",
      destination: "Kenya",
      country: "Kenya",
      reviewScore: 4.9,
      reviewCount: 450,
      amenities: ["Champagne Breakfast", "Certificate", "Transfer", "Pilot"],
      price: 35000,
      currency: "USD",
      productType: "ACTIVITY",
    },
    {
      externalId: "act-ken-002",
      name: "Maasai Village Visit & Sunset Bush Dinner",
      description: "Learn beadwork from Maasai women, then dine by candlelight in the savanna.",
      destination: "Kenya",
      country: "Kenya",
      reviewScore: 4.8,
      reviewCount: 320,
      amenities: ["Maasai Guide", "Traditional Meal", "Beadwork", "Dance", "Transfer"],
      price: 15000,
      currency: "USD",
      productType: "ACTIVITY",
    },
  ],
};

export class MockActivityAdapter extends BaseAdapter {
  name = "mock-activity-provider";
  productTypes = ["ACTIVITY"] as const;

  async fetchPrices(query: PriceQuery): Promise<FetchedProduct[]> {
    await this.delay(200 + Math.random() * 500);

    const key = Object.keys(MOCK_ACTIVITIES).find((k) =>
      query.destination.toLowerCase().includes(k.toLowerCase()) ||
      k.toLowerCase().includes(query.destination.toLowerCase())
    );

    if (!key) return [];

    const activities = MOCK_ACTIVITIES[key];
    return activities.map((a) => ({
      ...a,
      price: Math.round(a.price * (0.95 + Math.random() * 0.1)),
    }));
  }
}
