import { db } from "@/lib/db";

export async function seedBudgetTiers() {
  const tiers = [
    {
      slug: "horizon",
      name: "Horizon",
      description: "Essential departures to beautiful nearby routes. Perfect for long weekends and first journeys together.",
      minPrice: 200000,
      maxPrice: 400000,
      defaultMonths: 12,
      minMonths: 6,
      maxMonths: 24,
      destinations: JSON.stringify(["Bali", "Mexico", "Costa Rica", "Portugal", "Morocco"]),
      hotelStars: 3.5,
      inflationBuffer: 0.10,
      repriceTriggerMonths: 6,
      accentColor: "#C9A87C",
    },
    {
      slug: "meridian",
      name: "Meridian",
      description: "Elevated experiences on iconic routes. The sweet spot for milestone departures and celebration routes.",
      minPrice: 400000,
      maxPrice: 800000,
      defaultMonths: 24,
      minMonths: 12,
      maxMonths: 36,
      destinations: JSON.stringify(["Santorini", "Amalfi Coast", "Maldives", "Kyoto", "Swiss Alps"]),
      hotelStars: 4.5,
      inflationBuffer: 0.15,
      repriceTriggerMonths: 12,
      accentColor: "#C97B7B",
    },
    {
      slug: "celestial",
      name: "Celestial",
      description: "Rare journeys to the world's most extraordinary routes. For milestone celebrations.",
      minPrice: 800000,
      maxPrice: 1500000,
      defaultMonths: 36,
      minMonths: 18,
      maxMonths: 48,
      destinations: JSON.stringify(["Bora Bora", "Seychelles", "Patagonia", "Safari Kenya", "Northern Lights Norway"]),
      hotelStars: 5,
      inflationBuffer: 0.18,
      repriceTriggerMonths: 12,
      accentColor: "#D4A574",
    },
    {
      slug: "astral",
      name: "Astral",
      description: "Transcendent departures beyond the ordinary. Private charters, remote expeditions, and routes reserved for the few.",
      minPrice: 1500000,
      maxPrice: 5000000,
      defaultMonths: 48,
      minMonths: 24,
      maxMonths: 60,
      destinations: JSON.stringify(["Private Island Buyout", "Antarctica Expedition", "Around-the-World", "Safari + Seychelles Combo"]),
      hotelStars: 5,
      inflationBuffer: 0.20,
      repriceTriggerMonths: 18,
      accentColor: "#E8C9A0",
    },
  ];

  for (const tier of tiers) {
    await db.budgetTier.upsert({
      where: { slug: tier.slug },
      update: tier,
      create: tier,
    });
  }

  return tiers.length;
}

export async function seedPackageTemplates() {
  const templates = [
    // Meridian tier
    {
      slug: "santorini-sunset",
      title: "Santorini Sunset",
      subtitle: "Aegean Romance",
      description: "Experience the magic of Santorini with your loved one. From private sunset dinners in Oia to wine tastings at volcanic vineyards.",
      destination: "Santorini, Greece",
      image: "https://images.unsplash.com/photo-1613395877344-13d4c79e4284?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([
        "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=400&h=300&fit=crop",
      ]),
      basePrice: 499900,
      duration: 7,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "maldives-paradise",
      title: "Maldives Paradise",
      subtitle: "Overwater Dreams",
      description: "Wake up above crystal-clear turquoise waters in your private overwater villa. The ultimate couples retreat.",
      destination: "Maldives",
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([
        "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400&h=300&fit=crop",
      ]),
      basePrice: 829900,
      duration: 10,
      category: "HONEYMOON",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "kyoto-blossoms",
      title: "Kyoto Blossoms",
      subtitle: "Cherry Blossom Season",
      description: "Riverboat arrival to a secluded ryokan in the Arashiyama bamboo groves. Experience Japan's most romantic season.",
      destination: "Kyoto, Japan",
      image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 629900,
      duration: 12,
      category: "ANNIVERSARY",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "amalfi-coast",
      title: "Amalfi Coast",
      subtitle: "Italian Riviera",
      description: "Drive the winding coastal road from Positano to Ravello. Lemon groves, cliffside villas, and the bluest sea you've ever seen.",
      destination: "Amalfi Coast, Italy",
      image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 579900,
      duration: 8,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "swiss-alps",
      title: "Swiss Alps",
      subtitle: "Mountain Magic",
      description: "Private chalet in Zermatt with uninterrupted Matterhorn views. Fondue by the fire and glacier train adventures.",
      destination: "Zermatt, Switzerland",
      image: "https://images.unsplash.com/photo-1531310197839-ccf54634509e?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 689900,
      duration: 7,
      category: "ANNIVERSARY",
      isActive: true,
      isPremium: false,
    },
    // Horizon tier
    {
      slug: "bali-retreat",
      title: "Bali Retreat",
      subtitle: "Island of the Gods",
      description: "Ubud jungle villas, temple sunsets, and private pool days. Bali is where romance meets spirituality.",
      destination: "Bali, Indonesia",
      image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 289900,
      duration: 10,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "tulum-mexico",
      title: "Tulum Departure",
      subtitle: "Mayan Riviera",
      description: "Beachfront eco-luxury on the Caribbean coast. Cenote swims, Mayan ruins, and barefoot dinners.",
      destination: "Tulum, Mexico",
      image: "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 249900,
      duration: 7,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "costa-rica",
      title: "Costa Rica",
      subtitle: "Pura Vida",
      description: "Zip-line through cloud forests, soak in volcanic hot springs, and sleep in treetop lodges.",
      destination: "Costa Rica",
      image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 219900,
      duration: 8,
      category: "ADVENTURE",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "portugal-coast",
      title: "Portugal Coast",
      subtitle: "Atlantic Charm",
      description: "From Lisbon's yellow trams to the Algarve's sea caves. Wine, seafood, and endless coastline.",
      destination: "Algarve, Portugal",
      image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 269900,
      duration: 8,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "morocco-marrakech",
      title: "Morocco Magic",
      subtitle: "Souks & Sahara",
      description: "Riad living in Marrakech, camel treks to desert camps, and starlit dinners on the dunes.",
      destination: "Marrakech, Morocco",
      image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 239900,
      duration: 9,
      category: "ADVENTURE",
      isActive: true,
      isPremium: false,
    },
    // Celestial tier
    {
      slug: "bora-bora",
      title: "Bora Bora",
      subtitle: "Pearl of the Pacific",
      description: "Mount Otemanu rises from a turquoise lagoon. Your overwater bungalow has a glass floor and a private plunge pool.",
      destination: "Bora Bora",
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 1199900,
      duration: 10,
      category: "HONEYMOON",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "seychelles",
      title: "Seychelles",
      subtitle: "Granite Paradise",
      description: "Giant tortoises, pink granite boulders, and beaches that regularly top world's-best lists.",
      destination: "Seychelles",
      image: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 999900,
      duration: 10,
      category: "HONEYMOON",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "patagonia",
      title: "Patagonia",
      subtitle: "End of the World",
      description: "Trek the W Circuit, witness Perito Moreno glacier calving, and stay in remote eco-domes under the stars.",
      destination: "Patagonia, Argentina",
      image: "https://images.unsplash.com/photo-1518182170546-0766bc6f9213?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 849900,
      duration: 12,
      category: "ADVENTURE",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "safari-kenya",
      title: "Kenyan Safari",
      subtitle: "Wild & Romantic",
      description: "Maasai Mara game drives at dawn, bush dinners under acacia trees, and luxury tented camps.",
      destination: "Kenya",
      image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 929900,
      duration: 9,
      category: "ADVENTURE",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "northern-lights",
      title: "Northern Lights",
      subtitle: "Arctic Wonder",
      description: "Glass igloos in Finnish Lapland. Snowmobiling, reindeer sleighs, and aurora hunting from your bed.",
      destination: "Tromsø, Norway",
      image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 779900,
      duration: 7,
      category: "WINTER",
      isActive: true,
      isPremium: false,
    },
    // Astral tier
    {
      slug: "private-island",
      title: "Private Island Buyout",
      subtitle: "Yours Alone",
      description: "An entire island in the Caribbean or Pacific. Staff of 30. Your own chef, boat captain, and massage therapist.",
      destination: "Caribbean Private Island",
      image: "https://images.unsplash.com/photo-1540206351-d6465b3ac5c1?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 2499900,
      duration: 7,
      category: "LUXURY",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "antarctica-expedition",
      title: "Antarctica Expedition",
      subtitle: "The White Continent",
      description: "Fly the Drake. Cross the Antarctic Circle. Sleep on ice. Penguins, whales, and icebergs the size of cities.",
      destination: "Antarctica",
      image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 1899900,
      duration: 12,
      category: "EXPEDITION",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "around-the-world",
      title: "Around the World",
      subtitle: "Four Continents",
      description: "21 days. Tokyo, Maldives, Santorini, New York. Private jets. The departure that defines a lifetime.",
      destination: "Multi-Destination",
      image: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 3499900,
      duration: 21,
      category: "LUXURY",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "safari-seychelles",
      title: "Safari + Seychelles",
      subtitle: "Bush to Beach",
      description: "Five days on the Mara, then five days on a private Seychelles island. The ultimate milestone departure combo.",
      destination: "Kenya & Seychelles",
      image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 2199900,
      duration: 12,
      category: "LUXURY",
      isActive: true,
      isPremium: true,
    },
    {
      slug: "paris-romance",
      title: "Paris Romance",
      subtitle: "City of Light",
      description: "Private Seine cruise, dinner at the Eiffel Tower, and a suite at the Ritz. The classic never dies.",
      destination: "Paris, France",
      image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 459900,
      duration: 6,
      category: "HONEYMOON",
      isActive: true,
      isPremium: false,
    },
    {
      slug: "dubai-luxury",
      title: "Dubai Luxury",
      subtitle: "Desert Opulence",
      description: "Burj Al Arab suite, desert safari with dinner under the stars, and a private yacht on the marina.",
      destination: "Dubai, UAE",
      image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=600&fit=crop",
      gallery: JSON.stringify([]),
      basePrice: 529900,
      duration: 7,
      category: "LUXURY",
      isActive: true,
      isPremium: true,
    },
  ];

  for (const tmpl of templates) {
    await db.packageTemplate.upsert({
      where: { slug: tmpl.slug },
      update: tmpl,
      create: tmpl,
    });
  }

  // Link templates to tiers based on price
  const allTiers = await db.budgetTier.findMany();
  for (const tmpl of templates) {
    const tier = allTiers.find(
      (t) => tmpl.basePrice >= t.minPrice && tmpl.basePrice <= t.maxPrice
    );
    if (tier) {
      await db.packageTemplate.update({
        where: { slug: tmpl.slug },
        data: { tierId: tier.id },
      });
    }
  }

  return templates.length;
}
